Silence ansible fqcn error about vagrant module.
ansible-community/molecule-vagrant pull request #191
Opened 2022-10-11 07:37 UTC by apatard

The local vagrant module is not (yet?) inside a collection, so there's no FQCN. Add needed noqa bits.

Signed-off-by: Arnaud Patard <apatard@hupstream.com>

2022-10-11 07:51 UTC, ssbarnea requested changes
I would advise towards switching to a collection. It would be the wise thing to do, much better than adding noqa.

2022-10-11 08:07 UTC, apatard commented
> I would advise towards switching to a collection. It would be the wise thing to do, much better than adding noqa.

Sure, this PR is the short term solution. The mid/long one is clearly to create a collection. The main blocker was python-vagrant but it's not the case anymore. Now, I need to find time and to understand how it to do that properly. I'd like also that current PR (maybe except the doc one) should either be merge or closed before, so that we start with a clean state.

2022-10-14 16:48 UTC, apatard commented
@ssbarnea what about this PR ? would it make sens to create also a draft PR for removing the noqa flag and using community.vagrant.vagrant as module name ?

2022-12-24 14:54 UTC, ssbarnea approved these changes

2022-12-24 14:54 UTC, merged