update GH actions
ansible-community/molecule-vagrant pull request #200
Opened 2022-12-07 18:30 UTC by konstruktoid

This PR:
- Updates the GitHub actions, since Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

Signed-off-by: Thomas Sjögren <konstruktoid@users.noreply.github.com>

2022-12-07 19:24 UTC, ssbarnea requested changes
For python you also want to add `cache: pip` argument, to enable wheel caching.

2022-12-07 22:50 UTC, konstruktoid commented
> For python you also want to add `cache: pip` argument, to enable wheel caching.

done

2022-12-07 23:12 UTC, konstruktoid commented
The actions now fails because of:

"Error: No file in /Users/runner/work/molecule-vagrant/molecule-vagrant matched to [**/requirements.txt], make sure you have checked out the target repository" (https://github.com/ansible-community/molecule-vagrant/actions/runs/3643522742/jobs/6151833468#step:6:10)
"Error: Unexpected end of JSON input" (https://github.com/ansible-community/molecule-vagrant/actions/runs/3643522742/jobs/6151833356#step:17:2, https://github.com/ansible-community/molecule-vagrant/actions/runs/3643522742/jobs/6151833721#step:17:2)

2022-12-08 12:03 UTC, konstruktoid commented
should we split pyX,pyX-devel? the devel environments are failing.

2022-12-09 15:04 UTC, ssbarnea commented
> should we split pyX,pyX-devel? the devel environments are failing.

I would try to avoid the split as it would make entire pipeline much slower. I would try to fix the issue. Is not very common for devel to break the ci.

2022-12-09 15:16 UTC, konstruktoid commented
True, will investigate where `UserWarning: Usage of dash-separated 'home-page' will not be supported in future versions. Please use the underscore name 'home_page' instead` actually comes from.

2022-12-09 16:08 UTC, apatard commented
from a quick grep, I'm wondering where the tools are finding a python_requires with a 2.7 value in our repos...

2022-12-09 16:49 UTC, konstruktoid commented
> from a quick grep, I'm wondering where the tools are finding a python_requires with a 2.7 value in our repos...

exactly, or `home-page`.

2022-12-22 22:46 UTC, konstruktoid commented
🤷‍♂️

2022-12-24 09:09 UTC, closed without merging